export const USER_DECK = Object.freeze({
  // success
  CARD_LIST_SUCCESS: 'CARD_LIST_SUCCESS',
  CARD_DETAIL_SUCCESS: 'CARD_DETAIL_SUCCESS',
  CARD_UPDATE_SUCCESS: 'CARD_UPDATE_SUCCESS',
  CARD_DELETE_SUCCESS: 'CARD_DELETE_SUCCESS',
  CARD_CREATE_SUCCESS: 'CARD_CREATE_SUCCESS',
  TOPIC_LIST_SUCCESS: 'TOPIC_LIST_SUCCESS',
  TOPIC_DETAIL_SUCCESS: 'TOPIC_DETAIL_SUCCESS',
  TOPIC_UPDATE_SUCCESS: 'TOPIC_UPDATE_SUCCESS',
  TOPIC_DELETE_SUCCESS: 'TOPIC_DELETE_SUCCESS',
  TOPIC_CREATE_SUCCESS: 'TOPIC_CREATE_SUCCESS',
  DECK_DELETE_SUCCESS: 'DECK_DELETE_SUCCESS',
  DECK_UPDATE_SUCCESS: 'DECK_UPDATE_SUCCESS',
  DECK_DETAIL_SUCCESS: 'DECK_DETAIL_SUCCESS',
  MY_DECK_LIST_SUCCESS: 'MY_DECK_LIST_SUCCESS',
  DECK_CREATE_SUCCESS: 'DECK_CREATE_SUCCESS',
  CARD_IMPORT_SUCCESS: 'CARD_IMPORT_SUCCESS',
  // error
  DECK_NOT_FOUND: 'DECK_NOT_FOUND',
  DECK_OR_TOPIC_NOT_FOUND: 'DECK_OR_TOPIC_NOT_FOUND',
  DECK_OR_CARD_NOT_FOUND: 'DECK_OR_CARD_NOT_FOUND',
  MAX_DECKS_REACHED: 'MAX_DECKS_REACHED',
  FILE_URL_REQUIRED: 'FILE_URL_REQUIRED',
  MODE_INVALID: 'MODE_INVALID',
  IMPORT_PERMISSION_DENIED: 'IMPORT_PERMISSION_DENIED',
  EXPORT_PERMISSION_DENIED: 'EXPORT_PERMISSION_DENIED',
  TOPIC_NOT_BELONG_TO_DECK: 'TOPIC_NOT_BELONG_TO_DECK',
  TOPIC_NOT_FOUND: 'TOPIC_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
});

export const USER_DECK_MESSAGES = {
  CARD_LIST_SUCCESS: 'Cards retrieved successfully',
  CARD_DETAIL_SUCCESS: 'Card detail retrieved successfully',
  CARD_UPDATE_SUCCESS: 'Card updated successfully',
  CARD_DELETE_SUCCESS: 'Card deleted successfully',
  CARD_CREATE_SUCCESS: 'Card created successfully',
  TOPIC_LIST_SUCCESS: 'Topics retrieved successfully',
  TOPIC_DETAIL_SUCCESS: 'Topic detail retrieved successfully',
  TOPIC_UPDATE_SUCCESS: 'Topic updated successfully',
  TOPIC_DELETE_SUCCESS: 'Topic deleted successfully',
  TOPIC_CREATE_SUCCESS: 'Topic created successfully',
  DECK_DELETE_SUCCESS: 'Deck deleted successfully',
  DECK_UPDATE_SUCCESS: 'Deck updated successfully',
  DECK_DETAIL_SUCCESS: 'Deck detail retrieved successfully',
  MY_DECK_LIST_SUCCESS: 'Your decks retrieved successfully',
  DECK_CREATE_SUCCESS: 'Deck created successfully',
  DECK_NOT_FOUND: 'Deck not found',
  DECK_OR_TOPIC_NOT_FOUND: 'Deck or topic not found',
  DECK_OR_CARD_NOT_FOUND: 'Deck or card not found',
  MAX_DECKS_REACHED: 'You have reached the maximum number of decks allowed',
  CARD_IMPORT_SUCCESS: 'Cards imported successfully',
  FILE_URL_REQUIRED: 'File URL is required',
  MODE_INVALID: 'Invalid mode',
  IMPORT_PERMISSION_DENIED: "You don't have permission to import into this deck. Only the owner can import",
  EXPORT_PERMISSION_DENIED: "You don't have permission to export this deck",
  TOPIC_NOT_BELONG_TO_DECK: 'Topic is not belong to the selected deck',
  TOPIC_NOT_FOUND: 'Topic not found',
  USER_NOT_FOUND: 'User not found',
};
