@startuml Reset_Password_Sequence
skinparam sequenceArrowThickness 1.5
skinparam roundcorner 8
skinparam responseMessageBelowArrow true
skinparam sequenceGroupBorderThickness 1.5

skinparam participant {
    BackgroundColor #EEF4FF
    BorderColor     #4A7CFF
    FontStyle       Bold
}
skinparam actor {
    BackgroundColor #FEFEFE
    BorderColor     #333333
}
skinparam sequence {
    LifeLineBorderColor  #888888
    GroupBorderColor     #888888
    GroupBodyBackgroundColor #FAFAFA
    DividerBackgroundColor   #E8E8E8
}
actor       "Khách vãng lai"    as User
participant "UserController"     as controller
participant "UserService"      as service
database    "Database" as DB

User -> controller : sendResetPasswordOTP(email)
activate controller

controller   -> service : sendResetPasswordOTP(email)
activate service

service  -> DB  : findUserByEmail(email)
activate DB
DB   --> service : user
deactivate DB

alt user = null
    service  --> controller : userNotFoundError
    controller   --> User : Thông báo lỗi:\n"Email chưa được đăng ký hoặc sai định dạng"

else user != null
    service  -> service  : otp = generateOTP()
    service  -> DB   : saveOTP(otp)
    activate DB
    DB   --> service : result
    deactivate DB

    service --> User: Gửi email chứa mã OTP
    service  --> controller  : result
    controller  --> User : Thông báo thành công,\nChuyển sang trang Đặt lại mật khẩu
end

deactivate service
deactivate controller

User -> controller  : resetPassword(opt, newPassword, confirmPassword)

controller -> service  : resetPassword(opt, newPassword, confirmPassword)

service -> service  : validateResetPassword(opt, newPassword, confirmPassword)

service --> controller: result

alt result.success = false
    alt result.cause = "OTP"
        controller   --> User : Thông báo lỗi: "OTP sai hoặc hết hạn"
    else result.cause = "Password"
        controller   --> User : Thông báo lỗi: "Mật khẩu không hợp lệ"
    end
else result.success = true
    service  -> service  : hashPassword = hashPassword(newPassword)

    service  -> DB : updatePasswordByUserId(user.id, hashPassword)
    activate DB
    DB   --> service : result
    deactivate DB

    service  -> DB : deleteOTP(otp)
    activate DB
    DB   --> service : result
    deactivate DB

    service  --> controller : result
    controller   --> User : Thông báo "Đổi mật khẩu thành công!"\n, Chuyển hướng về trang Đăng nhập
end
deactivate controller
@enduml
